services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: rag-zookeeper
    restart: always
    ports:
      - "2181:2181"
    env_file:
      - .env
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - rag-network

  kafka:
    image: bitnami/kafka:latest
    container_name: rag-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - rag-network

  rag-news-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-news-app
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - rag-network
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  rag-network:
    driver: bridge
volumes:
  data: