services:  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: rag-zookeeper
    restart: always
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: bitnami/kafka:latest
    container_name: rag-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env

volumes:
  data: